version: '2'
services:
  simpledictionary-app:
    image: simpledictionary
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://simpledictionary-postgresql:5432/simpleDictionary
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  simpledictionary-postgresql:
    extends:
      file: postgresql.yml
      service: simpledictionary-postgresql
