version: '2'
services:
  simpledictionary-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/simpleDictionary/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpleDictionary
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
